### ISSUE TITLE
Filename supporting date formatting

### ISSUE THREAD

**Issue by mikemarsian** [nicholaspufal/invoice_creator#3]
Would love for invoice-creator's "filename" setting in config.yml to support date formatting, so that one could set
```
settings:
  ...
  date_format: "%b %d, %Y"
  filename: "invoice-%Y.%m.pdf"
```
